import Link from 'next/link';
import { ArrowLeft, Sparkles } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service',
};

export default function TermsPage() {
  return (
    <main className="deep-space-bg min-h-screen text-slate-100">
      <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="mb-8 flex items-center justify-between gap-4">
          <Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-300 hover:text-white transition-colors">
            <ArrowLeft className="h-4 w-4" />
            Back to home
          </Link>
          <div className="flex items-center gap-2">
            <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-600 to-violet-600 shadow-lg shadow-indigo-500/30">
              <Sparkles className="h-4 w-4 text-white" aria-hidden />
            </span>
            <span className="text-sm font-semibold tracking-tight gradient-text-premium">expressiveai.online</span>
          </div>
        </div>

        <article className="glass-card rounded-3xl border border-white/10 p-6 sm:p-10">
          <p className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-violet-300">Legal</p>
          <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">Terms of Service</h1>
          <p className="mt-3 text-sm text-slate-400">Last updated: September 2026</p>

          <div className="mt-8 space-y-8 text-sm leading-7 text-slate-300">
            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">1. Acceptance of terms</h2>
              <p>
                By accessing or using ExpressiveAI, you agree to be bound by these Terms of Service and all applicable laws and regulations.
                If you do not agree, please do not use our platform, website, or services.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">2. Description of service</h2>
              <p>
                ExpressiveAI provides AI-powered media generation tools, workflow access, account management, and related digital services.
                We may update, modify, or discontinue features at any time without prior notice to improve performance, reliability, or compliance.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">3. User accounts and eligibility</h2>
              <p>
                You must be at least 18 years old or have the legal capacity to enter into binding agreements in your jurisdiction.
                You are responsible for maintaining the confidentiality of your account, login credentials, and any activity under your account.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">4. Acceptable use</h2>
              <p>
                You agree not to use the service to generate or distribute illegal, harmful, abusive, deceptive, pornographic, hateful,
                threatening, or otherwise unlawful content. You may not attempt to evade rate limits, manipulate billing, reverse-engineer
                platform safeguards, or interfere with other users’ access to the service.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">5. Credits, subscriptions, and billing</h2>
              <p>
                Certain features may require credits, subscriptions, or other paid access. We may change pricing, features, or billing terms
                with reasonable notice where required by law. Unused credits or subscription periods may be subject to platform terms and expiry policies.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">6. Intellectual property</h2>
              <p>
                You retain ownership of the prompt text, source materials, and content you submit to the service, subject to the rights granted
                to us to process, store, and operate the platform. ExpressiveAI retains ownership of the underlying platform, software, branding,
                templates, workflows, and generated interfaces, except where specified otherwise by law or third-party licensor terms.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">7. Content and output</h2>
              <p>
                Output generated by AI may be imperfect, inconsistent, or subject to errors. You are responsible for reviewing final content,
                verifying factual accuracy, and ensuring the output complies with applicable laws, platform rules, and your intended use.
                We do not guarantee that any output will be suitable for any specific purpose or legal requirement.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">8. Watermarks and security</h2>
              <p>
                We may apply forensic watermarking, metadata, or other technical safeguards to outputs as part of our anti-abuse and trust framework.
                You agree not to remove, obscure, or evade such measures unless expressly authorized in writing.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">9. Limitation of liability</h2>
              <p>
                To the fullest extent permitted by law, ExpressiveAI is not liable for indirect, incidental, consequential, special, or punitive damages,
                including loss of data, business interruption, loss of goodwill, or similar losses arising from your use or inability to use the service.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">10. Termination</h2>
              <p>
                We may suspend or terminate access to the service if we determine that you have violated these terms, misused the platform,
                or created operational, legal, or security risk. You may stop using the service at any time.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-lg font-semibold text-white">11. Governing law</h2>
              <p>
                These terms are governed by the laws of the jurisdiction in which ExpressiveAI operates, without regard to conflict of law principles.
                If a dispute cannot be resolved informally, the parties may seek remedies available under applicable law.
              </p>
            </section>
          </div>

          <div className="mt-10 rounded-2xl border border-violet-500/30 bg-violet-500/5 p-4 text-sm text-slate-300">
            Questions about these terms? Contact us at <a href="mailto:legal@expressiveai.online" className="text-violet-300 underline">legal@expressiveai.online</a>.
          </div>
        </article>
      </div>
    </main>
  );
}
