'use client';

import { motion } from 'framer-motion';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { PlayCircle, ShieldCheck } from 'lucide-react';

interface Video {
  id: string;
  thumbnail_url: string;
  video_url: string;
  prompt: string;
  view_count: number;
}

export default function GalleryPage() {
  const [videos, setVideos] = useState<Video[]>([]);
  const [loading, setLoading] = useState(true);

  // In a real app we'd fetch from /api/generate/public or Supabase directly.
  // For this complete boilerplate, we'll implement a mock gallery list as placeholder 
  // since this requires a public video route.
  useEffect(() => {
    // Simulated fetch
    setTimeout(() => {
      setVideos([
        {
          id: 'v1',
          thumbnail_url: 'https://images.unsplash.com/photo-1682687982501-1e5898cb89e8?auto=format&fit=crop&w=600&q=80',
          video_url: '#',
          prompt: 'A cyberpunk city glowing in neon pink and cyan at midnight, rain pouring...',
          view_count: 1245,
        },
        {
          id: 'v2',
          thumbnail_url: 'https://images.unsplash.com/photo-1682687981922-7b55f5f4b595?auto=format&fit=crop&w=600&q=80',
          video_url: '#',
          prompt: 'Surreal landscape of floating islands with waterfalls falling into the abyss',
          view_count: 852,
        },
        {
          id: 'v3',
          thumbnail_url: 'https://images.unsplash.com/photo-1682687218904-de46ed992b58?auto=format&fit=crop&w=600&q=80',
          video_url: '#',
          prompt: 'Hyperrealistic portrait of a golden retriever astronaut on mars',
          view_count: 3102,
        },
        {
          id: 'v4',
          thumbnail_url: 'https://images.unsplash.com/photo-1682685797500-1c5c5c06d042?auto=format&fit=crop&w=600&q=80',
          video_url: '#',
          prompt: 'Time-lapse of a cherry blossom tree blooming in spring',
          view_count: 531,
        }
      ]);
      setLoading(false);
    }, 1000);
  }, []);

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <nav className="bg-white/70 backdrop-blur-md border-b border-gray-200 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">
          <Link href="/" className="text-xl font-semibold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
             expressiveai.online
          </Link>
          <div className="flex items-center gap-4">
             <Link href="/pricing" className="text-gray-600 hover:text-gray-900 transition">Pricing</Link>
             <Link href="/dashboard" className="text-gray-600 hover:text-gray-900 transition">Dashboard</Link>
          </div>
        </div>
      </nav>

      <main className="flex-grow pt-12 pb-24 px-6 max-w-7xl mx-auto w-full">
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">Discover Inspiration</h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Explore the latest stunning videos generated by our creative community.
          </p>
        </div>

        {loading ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[1, 2, 3, 4, 5, 6].map(i => (
              <div key={i} className="bg-gray-200 h-64 rounded-3xl animate-pulse" />
            ))}
          </div>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {videos.map((vid, idx) => (
              <motion.div
                key={vid.id}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: idx * 0.1 }}
                className="group relative bg-black rounded-3xl overflow-hidden shadow-lg cursor-pointer transform transition-all hover:-translate-y-2 hover:shadow-2xl"
              >
                <img 
                  src={vid.thumbnail_url} 
                  alt={vid.prompt} 
                  className="w-full h-80 object-cover opacity-80 group-hover:opacity-60 transition duration-500"
                />
                
                <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                  <PlayCircle className="text-white w-16 h-16" />
                </div>

                <div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black/90 via-black/50 to-transparent">
                  <p className="text-white font-medium line-clamp-2 mb-2">"{vid.prompt}"</p>
                  <div className="flex items-center gap-4 text-xs text-gray-300">
                    <span className="flex items-center gap-1"><PlayCircle className="w-4 h-4"/> {vid.view_count.toLocaleString()} views</span>
                    <span className="flex items-center gap-1"><ShieldCheck className="w-4 h-4"/> Verified Match</span>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
